# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweet_sms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweet_sms.proto',
  package='TwitterAPIStreaming',
  syntax='proto3',
  serialized_pb=_b('\n\x0ftweet_sms.proto\x12\x13TwitterAPIStreaming\"\x8c\x02\n\nSMSMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x10\n\x08tweet_id\x18\x02 \x01(\x03\x12\x14\n\x0cmessage_text\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x14\n\x0cmedia_source\x18\x05 \x01(\t\x12\x15\n\rtext_language\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\x03\x12\x11\n\tuser_name\x18\x08 \x01(\t\x12\x18\n\x10user_screen_name\x18\t \x01(\t\x12\x15\n\ruser_location\x18\n \x01(\t\x12\x19\n\x11\x64\x65stinationServer\x18\x0b \x01(\t\x12\x17\n\x0f\x64\x65stinationPort\x18\x0c \x01(\x05\";\n\tTweet_SMS\x12.\n\x05smses\x18\x01 \x03(\x0b\x32\x1f.TwitterAPIStreaming.SMSMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SMSMESSAGE = _descriptor.Descriptor(
  name='SMSMessage',
  full_name='TwitterAPIStreaming.SMSMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='TwitterAPIStreaming.SMSMessage.message_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tweet_id', full_name='TwitterAPIStreaming.SMSMessage.tweet_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_text', full_name='TwitterAPIStreaming.SMSMessage.message_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='TwitterAPIStreaming.SMSMessage.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_source', full_name='TwitterAPIStreaming.SMSMessage.media_source', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_language', full_name='TwitterAPIStreaming.SMSMessage.text_language', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='TwitterAPIStreaming.SMSMessage.user_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='TwitterAPIStreaming.SMSMessage.user_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_screen_name', full_name='TwitterAPIStreaming.SMSMessage.user_screen_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_location', full_name='TwitterAPIStreaming.SMSMessage.user_location', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destinationServer', full_name='TwitterAPIStreaming.SMSMessage.destinationServer', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destinationPort', full_name='TwitterAPIStreaming.SMSMessage.destinationPort', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=309,
)


_TWEET_SMS = _descriptor.Descriptor(
  name='Tweet_SMS',
  full_name='TwitterAPIStreaming.Tweet_SMS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smses', full_name='TwitterAPIStreaming.Tweet_SMS.smses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=370,
)

_TWEET_SMS.fields_by_name['smses'].message_type = _SMSMESSAGE
DESCRIPTOR.message_types_by_name['SMSMessage'] = _SMSMESSAGE
DESCRIPTOR.message_types_by_name['Tweet_SMS'] = _TWEET_SMS

SMSMessage = _reflection.GeneratedProtocolMessageType('SMSMessage', (_message.Message,), dict(
  DESCRIPTOR = _SMSMESSAGE,
  __module__ = 'tweet_sms_pb2'
  # @@protoc_insertion_point(class_scope:TwitterAPIStreaming.SMSMessage)
  ))
_sym_db.RegisterMessage(SMSMessage)

Tweet_SMS = _reflection.GeneratedProtocolMessageType('Tweet_SMS', (_message.Message,), dict(
  DESCRIPTOR = _TWEET_SMS,
  __module__ = 'tweet_sms_pb2'
  # @@protoc_insertion_point(class_scope:TwitterAPIStreaming.Tweet_SMS)
  ))
_sym_db.RegisterMessage(Tweet_SMS)


# @@protoc_insertion_point(module_scope)
